spring:
  application:
    name: send-email
  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      uri: ${MONGO_URI}
  logging:
    level:
      org:
        springframework:
          data:
            mongodb:
              core:
                MongoTemplate: DEBUG
server:
  port: 9080
